title: Project
tabs:
  main:
    display: Main
    sections:
      -
        fields:
          -
            handle: title
            field:
              type: text
              required: true
              validate:
                - required
          -
            handle: content
            field:
              type: markdown
              display: Content
              localizable: true
          -
            handle: author
            field:
              type: users
              display: Author
              default: current
              localizable: true
              max_items: 1
          -
            handle: template
            field:
              type: template
              display: Template
              localizable: true
          -
            handle: media
            field:
              max_files: 2
              min_files: 1
              container: assets
              type: assets
              display: Media
          -
            handle: project_link
            field:
              type: link
              display: 'Project Link'
              instructions: 'Provide a link to the project'
          -
            handle: description
            field:
              type: text
              display: Description
              instructions: 'Provide a short description of the project'
      -
        display: 'New Section'
  sidebar:
    display: Sidebar
    sections:
      -
        fields:
          -
            handle: slug
            field:
              type: slug
              localizable: true
              validate: 'max:200'
          -
            handle: date
            field:
              type: date
              required: true
              default: now
              validate:
                - required
